/**
 * Emits the SQL that seeds `questions` and `answer_choices` from the original
 * Stage 1 bank in `lib/mock/questions.ts`.
 *
 * Writing SQL rather than calling Supabase directly keeps this runnable in a
 * sandbox with no outbound network, and the statement can be reviewed before it
 * touches the database.
 *
 *   npx tsx scripts/seed-questions.ts > /tmp/seed.sql
 */
import { MOCK_QUESTIONS } from "../lib/mock/questions";
import { domainSection } from "../lib/taxonomy";

function lit(value: string | null | undefined): string {
  if (value === null || value === undefined) return "null";
  return `'${value.replace(/'/g, "''")}'`;
}

function jsonLit(value: unknown): string {
  if (value === null || value === undefined) return "null";
  return `${lit(JSON.stringify(value))}::jsonb`;
}

function arrayLit(values: string[] | undefined): string {
  if (!values || values.length === 0) return "'{}'";
  return `ARRAY[${values.map(lit).join(", ")}]::text[]`;
}

const lines: string[] = [
  "-- Generated by scripts/seed-questions.ts. Do not edit by hand.",
  "begin;",
];

for (const q of MOCK_QUESTIONS) {
  const section = domainSection(q.domain);
  // Math questions in the original bank that carry an explicit expression are
  // the ones where a calculator is genuinely irrelevant; default to allowed.
  const calculatorAllowed = section === "math";

  lines.push(
    `insert into public.questions (
  id, section, domain, skill, difficulty, question_type,
  stem, passage, passage_secondary, expression, table_data, figure,
  correct_answer, accepted_answers, explanation,
  calculator_allowed, source, tags, estimated_time_seconds
) values (
  ${lit(q.id)}, ${lit(section)}::public.section, ${lit(q.domain)}, ${lit(q.skill)},
  ${lit(q.difficulty)}::public.difficulty, ${lit(q.type)}::public.question_type,
  ${lit(q.stem)}, ${lit(q.passage ?? null)}, ${lit(q.passageSecondary ?? null)},
  ${lit(q.expression ?? null)}, ${jsonLit(q.table ?? null)}, ${jsonLit(q.figure ?? null)},
  ${lit(
    q.type === "multiple_choice"
      ? (q.choices.find((c) => c.id === q.correctAnswer)?.label ?? q.correctAnswer)
      : q.correctAnswer,
  )},
  ${arrayLit(q.acceptedAnswers)}, ${lit(q.explanation)},
  ${calculatorAllowed}, ${lit("MOGSAT original (Stage 1)")}, ${arrayLit(["stage-1"])},
  ${q.estimatedTimeSeconds}
)
on conflict (id) do update set
  stem = excluded.stem,
  explanation = excluded.explanation,
  updated_at = now();`,
  );

  for (const choice of q.choices) {
    lines.push(
      `insert into public.answer_choices (question_id, label, text, expression, is_correct)
values (${lit(q.id)}, ${lit(choice.label)}, ${lit(choice.text)}, ${lit(choice.expression ?? null)}, ${
        choice.id === q.correctAnswer
      })
on conflict (question_id, label) do update set
  text = excluded.text,
  is_correct = excluded.is_correct;`,
    );
  }
}

lines.push("commit;");
console.log(lines.join("\n"));
